@baseUrl = http://localhost:5005
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/comment
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "6506c7c863641b1d62bf0403",
  "postId": "6507074f7e6b10cc31970e37",
  "comment": "This is my first comment",
  "profilePicture": "https://res.cloudinary.com/dbbeyjd5f/image/upload/v1694515084/65003f8b8655afe2a1c4be4a"
}


###
GET {{baseUrl}}/{{urlPath}}/post/comments/65056ad6896a5d19fb8ddf85
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/commentsnames/65056ad6896a5d19fb8ddf85
Content-Type: application/json
Accept: application/json
withCredentials: true

###
GET {{baseUrl}}/{{urlPath}}/post/single/comment/65056ad6896a5d19fb8ddf85/65064439fa71fbbd9ff16502
Content-Type: application/json
Accept: application/json
withCredentials: true
