@baseUrl = http://localhost:5005
@urlPath = api/v1

###
PUT {{baseUrl}}/{{urlPath}}/notification/650707dd7e6b10cc31970e42
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
DELETE {{baseUrl}}/{{urlPath}}/notification/650707dd7e6b10cc31970e42
Content-Type: application/json
Accept: application/json
withCredentials: true

{}

###
GET {{baseUrl}}/{{urlPath}}/notifications
Content-Type: application/json
Accept: application/json
withCredentials: true
